### ISSUE TITLE
Ruby >= 3.1 causes error during engine_cart:generate process

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1115]
```
Bundle complete! 11 Gemfile dependencies, 59 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
       rails  webpacker:install
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
rails aborted!
LoadError: cannot load such file -- net/smtp
/tmp/d20220124-2469-rajchb/internal/config/application.rb:11:in `<top (required)>'
/tmp/d20220124-2469-rajchb/internal/Rakefile:4:in `require_relative'
/tmp/d20220124-2469-rajchb/internal/Rakefile:4:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
[DEPRECATED] `Bundler.clean_system` has been deprecated in favor of `Bundler.unbundled_system`. If you instead want to run the command in the environment before bundler was originally loaded, use `Bundler.original_system` (called at /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/engine_cart-2.4.0/lib/engine_cart/tasks/engine_cart.rake:109)
[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/engine_cart-2.4.0/lib/engine_cart/tasks/engine_cart.rake:146)
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
You have requested:
  sprockets < 4

The bundle currently has sprockets locked at 4.0.2.
Try running `bundle update sprockets`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- net/smtp (LoadError)
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail.rb:9:in `<module:Mail>'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail.rb:3:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/actionmailbox-6.1.4.4/lib/action_mailbox/mail_ext.rb:3:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/actionmailbox-6.1.4.4/lib/action_mailbox.rb:3:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/actionmailbox-6.1.4.4/lib/action_mailbox/engine.rb:9:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/geoblacklight/geoblacklight/.internal_test_app/config/application.rb:11:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/command/actions.rb:22:in `require'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/command/actions.rb:22:in `require_application!'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/commands/generate/generate_command.rb:10:in `help'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/commands/generate/generate_command.rb:19:in `perform'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/command/base.rb:69:in `perform'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/command.rb:48:in `invoke'
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
rake aborted!
EngineCart failed on with: pid 3157 exit 1
/opt/hostedtoolcache/Ruby/3.1.0/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.1.0/x64/bin/bundle:25:in `<main>'
Tasks: TOP => ci => geoblacklight:generate => engine_cart:generate
```

**Comment by eliotjordan** [comment]
Upgrading to Ruby 3.1 necessitates upgrading sprockets which opens up a can of worms related to asset compilation. The smart move here is to wait and follow what the upstream Blacklight project does in this regard.

One tip, though: There is a problem installing `puma` in Ruby 3.0 with bundler (at least on current versions of MacOS). This can be addressed by configuring bundler:
```
bundle config set --global build.puma --with-cflags=-fms-extensions
```

**Comment by ewlarson** [comment]
Closing as GBL v4.0+ runs fine on Ruby 3.1.2 and Blacklight 7.29.0. Please reopen if necessary.
