### ISSUE TITLE
Faraday 0.9.2 NoMethod for 'params_encoder'

### ISSUE THREAD

**Issue by sgbalogh** [geoblacklight/geoblacklight#359]
Created a completely new Rails app to develop using the latest version of GeoBlacklight, and I keep running into a no method error from Faraday (0.9.2) whenever I try to use a generated download option. Rolling it back to 0.9.1 solves the problem.

Here is an abbreviated stack trace:
```
Started GET "/download/nyu_fales_1234_56789?type=jpg" for ::1 at 2015-12-01 12:30:15 -0500
Processing by DownloadController#show as JSON
  Parameters: {"type"=>"jpg", "id"=>"nyu_fales_1234_56789"}
Solr query: get select {:qt=>"document", :q=>"{!raw f=layer_slug_s v=$id}", :id=>"nyu_fales_1234_56789"}
Solr fetch (20.0ms)
Completed 500 Internal Server Error in 26ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `params_encoder' for {:timeout=>16, :open_timeout=>16}:Hash):
  faraday (0.9.2) lib/faraday/rack_builder.rb:192:in `build_env'
  faraday (0.9.2) lib/faraday/rack_builder.rb:139:in `build_response'
  faraday (0.9.2) lib/faraday/connection.rb:377:in `run_request'
  faraday (0.9.2) lib/faraday/connection.rb:140:in `get'
  /Users/sgb334/git/geoblacklight/lib/geoblacklight/download.rb:64:in `initiate_download'
  /Users/sgb334/git/geoblacklight/lib/geoblacklight/download.rb:41:in `create_download_file'
  /Users/sgb334/git/geoblacklight/lib/geoblacklight/download.rb:32:in `get'
  /Users/sgb334/git/geoblacklight/app/controllers/download_controller.rb:93:in `check_type'
  /Users/sgb334/git/geoblacklight/app/controllers/download_controller.rb:23:in `show'
```

Has anyone else run into this?

**Comment by sgbalogh** [comment]
Whoops, just saw this: https://github.com/geoblacklight/geoblacklight/commit/ffc09b36946d36211a8057f914a5489a80a6a4b5
