### ISSUE TITLE
Make shutdown of server task more graceful

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#485]
Shutdown in the `geoblacklight:server` task is not handled very well at the moment. Control+C looks like this:

```
^C[2016-08-05 17:54:45] INFO  going to shutdown ...
[2016-08-05 17:54:45] INFO  WEBrick::HTTPServer#start done.
Exiting
rake aborted!
Interrupt:
/Users/eliotj/.rvm/gems/ruby-2.3.1@pulmap/gems/geoblacklight-1.1.0/lib/tasks/geoblacklight.rake:10:in `system'
/Users/eliotj/.rvm/gems/ruby-2.3.1@pulmap/gems/geoblacklight-1.1.0/lib/tasks/geoblacklight.rake:10:in `block (4 levels) in <top (required)>'
/Users/eliotj/.rvm/gems/ruby-2.3.1@pulmap/gems/solr_wrapper-0.14.2/lib/solr_wrapper/instance.rb:213:in `with_collection'
/Users/eliotj/.rvm/gems/ruby-2.3.1@pulmap/gems/geoblacklight-1.1.0/lib/tasks/geoblacklight.rake:9:in `block (3 levels) in <top (required)>'
/Users/eliotj/.rvm/gems/ruby-2.3.1@pulmap/gems/solr_wrapper-0.14.2/lib/solr_wrapper/instance.rb:64:in `wrap'
/Users/eliotj/.rvm/gems/ruby-2.3.1@pulmap/gems/solr_wrapper-0.14.2/lib/solr_wrapper.rb:40:in `wrap'
/Users/eliotj/.rvm/gems/ruby-2.3.1@pulmap/gems/geoblacklight-1.1.0/lib/tasks/geoblacklight.rake:8:in `block (2 levels) in <top (required)>'
/Users/eliotj/.rvm/gems/ruby-2.3.1@pulmap/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/eliotj/.rvm/gems/ruby-2.3.1@pulmap/bin/ruby_executable_hooks:15:in `eval'
/Users/eliotj/.rvm/gems/ruby-2.3.1@pulmap/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => geoblacklight:server
(See full trace by running task with --trace)
```

**Comment by mejackreed** [comment]
I wonder if thats something that can happen in `solr_wrapper`?
