### ISSUE TITLE
RAILS_ENV=production installs are broken in v1.1+

### ISSUE THREAD

**Issue by pmather** [geoblacklight/geoblacklight#494]
Generating a new GeoBlacklight application by following the install instructions results in a `Gemfile` that includes this snippet:

```
group :development, :test do
  gem 'solr_wrapper', '>= 0.3'
end
```

When installing in `RAILS_ENV=production` mode we typically include `--without 'development test'` in the `bundle install` step.  This means the `solr_wrapper` gem is not installed, as per the `Gemfile` instructions.

Unfortunately, this means all subsequent `rake` tasks fail because in v1.1+ of the `geoblacklight` gem, the `solr_wrapper` gem is required unconditionally in the first line of `lib/tasks/geoblacklight.rake`.

E.g., something like this happens:

```
vagrant@vagrant-ubuntu-trusty-64:~/app-name$ bundle exec rake -T
rake aborted!
LoadError: cannot load such file -- solr_wrapper
/home/vagrant/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/home/vagrant/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/vagrant/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.gem/ruby/2.3.0/gems/geoblacklight-1.1.2/lib/tasks/geoblacklight.rake:1:in `<top (required)>'
/home/vagrant/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/vagrant/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/home/vagrant/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/vagrant/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/vagrant/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:654:in `block in run_tasks_blocks'
/home/vagrant/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:654:in `each'
/home/vagrant/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:654:in `run_tasks_blocks'
/home/vagrant/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:442:in `block in run_tasks_blocks'
/home/vagrant/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine/railties.rb:13:in `each'
/home/vagrant/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine/railties.rb:13:in `each'
/home/vagrant/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:442:in `run_tasks_blocks'
/home/vagrant/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:457:in `load_tasks'
/home/vagrant/app-name/Rakefile:6:in `<top (required)>'
/home/vagrant/.gem/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

(Note the `/home/vagrant/.gem/ruby/2.3.0/gems/geoblacklight-1.1.2/lib/tasks/geoblacklight.rake:1:in `<top (required)>'` line.)

Does this mean that `solr_wrapper` is required in all environments, even if you are using an external Solr core in `RAILS_ENV=production` mode?  This problem did not occur with v0.12.1 of the `geoblacklight` gem, and, looking at the code, does not look like it would be a problem prior to v1.1.0.

**Comment by pmather** [comment]
Pull request #495 appears to fix the problem for me.  Thanks!
