### ISSUE TITLE
NameError with Geoblacklight 1.1.2 and Blacklight 6.6.0

### ISSUE THREAD

**Issue by dmolesUC3** [geoblacklight/geoblacklight#499]
```
method `list' not defined in #<Class:0x007fd929f4c298>/Users/dmoles/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/ostruct.rb:225:in `remove_method'
/Users/dmoles/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/ostruct.rb:225:in `delete_field'
/Users/dmoles/.rvm/gems/ruby-2.2.3/gems/geoblacklight-1.1.2/lib/geoblacklight/engine.rb:13:in `<class:Engine>'
/Users/dmoles/.rvm/gems/ruby-2.2.3/gems/geoblacklight-1.1.2/lib/geoblacklight/engine.rb:11:in `<module:Geoblacklight>'
/Users/dmoles/.rvm/gems/ruby-2.2.3/gems/geoblacklight-1.1.2/lib/geoblacklight/engine.rb:10:in `<top (required)>'
```

When I drill in with the debugger, the ostruct in question looks to be a `Blacklight::NestedOpenStructWithHashAccess`, and it does have a `list` key, with a `Blacklight::Configuration::ViewConfig` value. 

The error seems to be on this line in `geoblacklight/engine.rb`:

```
Blacklight::Configuration.default_values[:view].delete_field('list')
```

**Comment by dmolesUC3** [comment]
If I change that line to

```
Blacklight::Configuration.default_values[:view].delete(:list)
```

it works, and (AFAICT) seems to do the right thing.

**Comment by dmolesUC3** [comment]
Downgrading to Blacklight 6.5.0 also seems to solve the problem, I'm not sure why -- it doesn't seem like `NestedOpenStructWithHashAccess` has changed since 2014 or so.

**Comment by mejackreed** [comment]
Thanks for reporting @dmolesUC3 !

**Comment by andrewbattista** [comment]
@mejackreed can you look at this one? Should it be closed or is it still a present bug?
