### ISSUE TITLE
spec/features/metadata_panel_spec randomly fails

### ISSUE THREAD

**Issue by jrgriffiniii** [geoblacklight/geoblacklight#832]
This does not need seem to fail consistently for me, but I've been finding that the following test failures can occur:

```ruby
1) Metadata tools when metadata references are available shows up as XML
     Failure/Error: expect(page).to have_css '.CodeRay'
       expected to find css ".CodeRay" within #<Capybara::Node::Element tag="div" path="/HTML/BODY[1]/DIV[3]/DIV[1]/DIV[1]/DIV[2]/DIV[1]"> but there were no matches
     # ./spec/features/metadata_panel_spec.rb:24:in `block (5 levels) in <top (required)>'
     # ./spec/features/metadata_panel_spec.rb:22:in `block (4 levels) in <top (required)>'
     # ./spec/features/metadata_panel_spec.rb:21:in `block (3 levels) in <top (required)>'
```

**Comment by jrgriffiniii** [comment]
This might be related to metadata downloads.  When I SSH into a CircleCI environment, I am able to reproduce the failure:

```bash
circleci@9b1f82851f4d:~/geoblacklight$ bundle exec rspec spec/features/metadata_panel_spec.rb
2019-08-01 19:39:12 WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
Capybara starting Puma...
* Version 3.12.1 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:38121
.F.

Failures:

  1) Metadata tools when metadata references are available shows up as XML
     Failure/Error: expect(page).to have_css '.CodeRay'
       expected to find css ".CodeRay" within #<Capybara::Node::Element tag="div" path="/HTML/BODY[1]/DIV[3]/DIV[1]/DIV[1]/DIV[2]/DIV[1]"> but there were no matches
     # ./spec/features/metadata_panel_spec.rb:24:in `block (5 levels) in <top (required)>'
     # ./spec/features/metadata_panel_spec.rb:22:in `block (4 levels) in <top (required)>'
     # ./spec/features/metadata_panel_spec.rb:21:in `block (3 levels) in <top (required)>'

Finished in 19.77 seconds (files took 2.36 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/features/metadata_panel_spec.rb:17 # Metadata tools when metadata references are available shows up as XML
```
(the session was https://circleci.com/gh/geoblacklight/geoblacklight/1069)

However, I cannot reproduce this locally.

**Comment by jrgriffiniii** [comment]
The test fails when a request is made to `http://purl.stanford.edu/fb897vt9938.mods`, and the following error is raised:

```ruby
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: dh key too small
```

**Comment by jrgriffiniii** [comment]
I can reproduce this with `curl` on the CircleCI environment:

```bash
circleci@9b1f82851f4d:~/geoblacklight$ curl -I "http://purl.stanford.edu/fb897vt9938.mods"
HTTP/1.0 302 Found
Location: https://purl.stanford.edu/fb897vt9938.mods
Server: BigIP
Connection: Keep-Alive
Content-Length: 0

circleci@9b1f82851f4d:~/geoblacklight$ curl -LI "http://purl.stanford.edu/fb897vt9938.mods"
HTTP/1.0 302 Found
Location: https://purl.stanford.edu/fb897vt9938.mods
Server: BigIP
Connection: Keep-Alive
Content-Length: 0

curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
```

**Comment by mejackreed** [comment]
@jrgriffiniii what if you modify the url to be `https://purl.stanford.edu/fb897vt9938.mods`?

**Comment by jrgriffiniii** [comment]
Sorry, it works locally, but I'll need to SSH into a new CircleCI container to test it (that's where it was consistently failing).  I can try it on another branch to speed up testing.

**Comment by jrgriffiniii** [comment]
@mejackreed That didn't seem to work with https://github.com/geoblacklight/geoblacklight/pull/829/commits/3b4c6ab32563fc97051d6fbdfed89ea3e5686745: https://circleci.com/gh/geoblacklight/geoblacklight/1078#queue-placeholder/containers/3

**Comment by mejackreed** [comment]
Bummer :( thats a curious error for sure . Thanks for taking this tricky one on!
