### ISSUE TITLE
Error starting server

### ISSUE THREAD

**Issue by MutantKiwi** [geoblacklight/geoblacklight#983]
Attempting to install Geoblacklight 3.1.0 on Windows 10

Install as per template using 3.1.0

When I try and start server

`rake geoblacklight:server`

I get the following error

```
'PS C:\Users\DellBoy\gbl> rake geoblacklight:server --trace
** Invoke geoblacklight:server (first_time)
** Execute geoblacklight:server
rake aborted!
Not started yet
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:152:in `block in create'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:151:in `create'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:215:in `with_collection'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/geoblacklight-3.1.0/lib/tasks/geoblacklight.rake:10:in `block (3 levels) in <main>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:64:in `wrap'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper.rb:43:in `wrap'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/geoblacklight-3.1.0/lib/tasks/geoblacklight.rake:9:in `block (2 levels) in <main>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
C:/Ruby26-x64/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
C:/Ruby26-x64/bin/rake:23:in `load'
C:/Ruby26-x64/bin/rake:23:in `<main>'
Tasks: TOP => geoblacklight:server'
```

Any ideas on how to resolve?

**Comment by mejackreed** [comment]
Do you have Java installed? Try running `bundle exec solr_wrapper` as a separate command and then `bin/rails server`

**Comment by MutantKiwi** [comment]
@mejackreed Thanks for your reply

Java is installed on the machine and is running correctly.

I ran `bundle exec solr_wrapper` but failed

```
PS C:\Users\DellBoy\gbl> bundle exec solr_wrapper
Starting Solr 8.6.3 on port 8983 ... Traceback (most recent call last):
        10: from C:/Ruby26-x64/bin/solr_wrapper:23:in `<main>'
         9: from C:/Ruby26-x64/bin/solr_wrapper:23:in `load'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/exe/solr_wrapper:113:in `<top (required)>'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:64:in `wrap'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/exe/solr_wrapper:114:in `block in <top (required)>'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:215:in `with_collection'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:151:in `create'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:152:in `block in create': Not started yet (RuntimeError)
PS C:\Users\DellBoy\gbl>
```
I am sure it is something simple. First time using Ruby on Rails...Demo Ruby on Rails app runs correctly.

**Comment by MutantKiwi** [comment]
Just to check I tried an earlier version of Geoblacklight (2.4.0) but fails with a Rails dependency (assume because I installed 6.0.3.4)

```
Resolving dependencies...
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 6.0.3, >= 6.0.3.4) x64-mingw32

    geoblacklight (~> 2.4.0) x64-mingw32 was resolved to 2.4.0, which depends on
      rails (~> 5.0) x64-mingw32
```

**Comment by mejackreed** [comment]
It seems like the issue here is a problem running `solr_wrapper`. `solr_wrapper` is a tool that allows you to run a local instance of solr for development and testing purposes. 

Do you have Java installed? If so what version? I think Java 8 is required for Solr.

**Comment by MutantKiwi** [comment]
@mejackreed Ok thanks I will give that a try

**Comment by ewlarson** [comment]
Closing as we organize our issues. @MutantKiwi please reopen this issue if you continue to have trouble running solr-wrapper.
